version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: America/Denver
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:30"
      timezone: America/Denver
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
